name    'arnoudj-sudo'
version '1.1.2'
summary 'Manage sudoers'
description 'Manage sudoers'
source 'git://github.com/arnoudj/arnoudj-sudo'
author 'Arnoud de Jonge'
license 'Apache License, Version 2.0'
